/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:16e7fd7e-3e56-4a17-8ba9-7313b09f810e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9LhjsLwiP",
    "aws_user_pools_web_client_id": "7fgvs50m0urlm7egbnkhric6id",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pannitsv7jbz5cz2qoa6gy4zb4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6scsjuohpzer7dvjwnhvzeoije",
    "aws_user_files_s3_bucket": "bucketrioblue24856-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
