/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:16e7fd7e-3e56-4a17-8ba9-7313b09f810e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9LhjsLwiP",
    "aws_user_pools_web_client_id": "7fgvs50m0urlm7egbnkhric6id",
    "oauth": {}
};


export default awsmobile;
